export const SET_SNACKBAR = "GLOBAL/SET_SNACKBAR";

export const SET_MODAL_CONFIRM = "GLOBAL/SET_MODAL_CONFIRM";

export const SET_MODAL_CONFIRM_ACCEPTED = "GLOBAL/SET_MODAL_CONFIRM_ACCEPTED";

export const SET_MODAL_CREATE_UPDATE = "GLOBAL/SET_MODAL_CREATE_UPDATE";

export const SET_MODAL_DATA_FORM = "GLOBAL/SET_MODAL_DATA_FORM";

export const GET_METAS = "GLOBAL/GET_METAS";
